# Site settings
title:
email:
description: > # this means to ignore newlines until "baseurl:"
  Personal site of Steven Sawtelle, student at Arizona State university,
  Software Engineering intern, and big fan of making Twitter bots.
baseurl: "/sawtelleme" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

# User setting
owner: Steven Sawtelle
email: steven.sawtelle@gmail.com
facebook_username:
twitter_username: StevenSawtelle
github_username: StevenSawtelle
address:
  - line:
  - line:
  # Feel free to add more lines here 
telephone: (623) 523-7572
copyright:

# API settings
google_api_key:

# Build settings
markdown: kramdown
