# Site settings
title:
email:
description: > # this means to ignore newlines until "baseurl:"
<<<<<<< HEAD
  Personal site of Steven Sawtelle, student at Arizona State university,
  Software Engineering intern, and big fan of making Twitter bots.
=======
  Steven - Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
>>>>>>> refs/remotes/origin/gh-pages
baseurl: "/sawtelleme" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

# User setting
owner: Steven Sawtelle
email: steven.sawtelle@gmail.com
facebook_username:
twitter_username: StevenSawtelle
github_username: StevenSawtelle
address:
  - line:
  - line:
  # Feel free to add more lines here 
telephone:
copyright:

# API settings
google_api_key:

# Build settings
markdown: kramdown
